#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations to meet the following requirements:
sudo apt update
sudo apt install -y haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Configure HAProxy
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
# Global settings
global
    log /dev/log    local0
    log /dev/log    local1 notice
    maxconn 200

# Default settings
defaults
    log     global
    option  httplog
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

# Frontend (client-side) configuration
frontend http_front
    bind *:80
    default_backend http_back

# Backend (server-side) configuration
backend http_back
    balance roundrobin
    server web-01 35.172.186.17:80 check
    server web-02 3.80.87.226:80 check
EOL

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Test the load balancer
echo "Testing HAProxy load balancing between web-01 and web-02"
curl -sI http://3.85.115.94 | grep X-Served-By
curl -sI http://3.85.115.94 | grep X-Served-By

# Output the final confirmation
echo "HAProxy has been configured and tested. Load balancing should alternate between web-01 and web-02."

