#!/usr/bin/env bash
#transfer files to a server

if [$# -lt 4]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
else
	scp -o "StrictHostKeyChecking=no" -i "$1" "$file" "$3@$2":~/
